config/routes.rb
Watchman::Application.routes.draw do
  get "flatuipro_demo/index"

  root 'watch#index'
  get  'events', to: 'events#index'
  get  'events/:event_id', to: 'events#show', constraints: { event_id: /[^\/]+/ }
  get  'exceptions/:event_id', to: 'logged_exceptions#show', constraints: { event_id: /[^\/]+/ }

end

app/models/event.rb
class Event < Sequel::Model(:logging_event)
  set_primary_key :event_id
  one_to_many :logged_exceptions, key: :event_id

  def self.top(num_events, after_id=0, log_level='info')
    Event.order_by(:event_id)
      .select(:event_id, :log_date, :formatted_message, :level_string,
              :thread_name, :logger_name, :caller_filename, :caller_method,
              :caller_line, :caller_class)
      .where('event_id > ?', after_id)
      .where(level_string: levels(log_level))
      .last(num_events)
  end

  private

  def self.levels(log_level)
    case log_level
    when "info"
      ['INFO', 'WARN', 'ERROR']
    when "warn"
      ['WARN', 'ERROR']
    when "error"
      'ERROR'
    end
  end
end

app/models/logged_exception.rb
class LoggedException < Sequel::Model(:logging_event_exception)
  many_to_one :event, key: :event_id

  def self.exception_details(event_id)
    LoggedException.where(event_id: event_id).all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def num_events
    cookies.permanent[:num_events] ||= Watchman.config.default_num_events
    cookies.permanent[:num_events].to_i
  end

  def log_level
    cookies.permanent[:log_level] ||= Watchman.config.default_log_level
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.top(num_events, params[:after].to_i, log_level)
  end

  def show
    event = Event.find(event_id: params[:event_id])
    respond_to do |format|
      format.json { render json: EventDetails.new(event).to_json }
    end
  end
end

app/controllers/flatuipro_demo_controller.rb
class FlatuiproDemoController < ApplicationController
  def index
  end
end

app/controllers/logged_exceptions_controller.rb
class LoggedExceptionsController < ApplicationController
  def show
    @exception_details = LoggedException.exception_details(params[:event_id])
  end
end

app/controllers/watch_controller.rb
class WatchController < ApplicationController
  def index
    @events = Event.top(num_events, 0, log_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def num_events
    @_controller.num_events
  end

  def log_level
    @_controller.log_level
  end

  def to_time(time)
    if time.class == Time
      time
    else
      Time.new(time)
    end
  end

  def escape_dot(event_id)
    event_id.to_s.gsub /\./, '\\\\.'
  end
end

app/views/events/_event.html.erb
<%= content_tag :tr, class: 'event', id: event.event_id, data: {id: event.event_id} do %>
  <td class='nowrap'><%= to_time(event.log_date).to_formatted_s(:short) %></td>
  <td><%= event.caller_class.split('.').last %></td>
  <td class='breakme'><%= event.formatted_message %></td>
  <td><%= event.level_string %></td>
<% end %>

app/views/events/index.js.erb
$('#events').prepend('<%= j render(@events) %>');
<% @events.each do |event| %>
  $('#<%= j escape_dot event.event_id %>').effect("highlight", {}, 1500);
<% end %>
$('.event').filter(function(i) { return i >= <%= num_events %>; }).remove();
EventPoller.poll();

app/views/layouts/_footer.html.erb
<footer class="bottom-menu bottom-menu-inverse">
  <div class="row">
    <div class="span2 brand">
      <a href="#">Watchman</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "Watchman", "#", class: "brand" %>
      <nav role="navigation">
        <ul class="nav">
          <li class="active"><%= link_to "Home", "#" %></li>
          <li><%= link_to "Exceptions", "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Watchman</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="wrapper">
    <div class="proper-content">

      <%= yield %>

      <div class="push"></div>
    </div>
  </div>

  <div class="footer-wrapper">
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/logged_exceptions/_exception_modal.html.erb
<div id="exceptionModal" class="modal" tabindex="-1" role="dialog" aria-hidden="false" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close fui-cross" data-dismiss="modal" aria-hidden="true"></button>
    <h3>Exception Details</h3>
  </div>

  <div class="modal-body">
    <% @exception_details.each do |detail| %>
      <span><%= detail.trace_line %></span>
    <% end %>
  </div>

  <div class="modal-footer">
    <button id="selectException" class="btn btn-primary">Select Exception</button>
  </div>
</div>

app/views/logged_exceptions/show.js.erb
$('body').prepend('<%=j render("exception_modal") %>');

app/views/watch/_event_table.html.erb
<table class="table table-hover" title="Event List">
  <thead>
    <tr>
      <th>Date</th>
      <th>Class</th>
      <th>Message</th>
      <th>Level</th>
    </tr>
  </thead>
  <%= content_tag :tbody, id: "events", data: {url: events_url} do %>
    <%= render @events %>
  <% end %>
</table>

app/views/watch/_filters.html.erb
<input type="text" name="num_events" pattern="[0-9]*" id="spinner-01" value="<%= num_events %>" class="spinner ui-spinner-input" aria-valuemin="1" aria-valuemax="9999">
<%# <%= select_tag "log_level", nil, class: 'mbn' %1> %>
<%#   <option value="info">INFO</option> %>
<%#   <option value="warn">WARN</option> %>
<%#   <option value="error">ERROR</option> %>
<%# <% end %1> %>
<select name="log_level" class="mbn" id="log_level">
  <%= options_for_select([["INFO", "info"], ["WARN", "warn"], ["ERROR", "error"]], log_level) %>
</select>

app/views/watch/_sidebar.html.erb
<aside class="well hidden m-sidebar affix breakme">
  <div class="row-fluid mbm">
    <div class="span4" id="eventID">
      <span class="label label-inverse">Event ID</span>
    </div>
    <div class="span4" id="thread">
      <span class="label label-inverse">Thread</span>
    </div>
    <div class="span4" id="level">
      <span class="label label-inverse">Level</span>
    </div>
  </div>
  <div class="row-fluid mbm" id="callerClass">
    <span class="label label-inverse">Caller Class</span>
  </div>
  <div class="row-fluid mbm">
    <div class="span6" id="callerMethod">
      <span class="label label-inverse">Caller Method</span>
    </div>
    <div class="span6" id="lineNumber">
      <span class="label label-inverse">Line Number</span>
    </div>
  </div>
  <div class="row-fluid mbm" id="formattedMessage">
    <span class="label label-inverse">Message</span>
  </div>
  <%= link_to "Exception Info", "#fakelink", id: "exceptionInfo", class: "btn btn-large btn-block disabled", data: {url: "#{root_url}exceptions/"} %>
</aside>

app/views/watch/index.html.erb
<div class="row">
  <div class="container-fluid">
    <div class="span">
        <div class="control-group">
          <%= render 'watch/filters' %>
        </div>
    </div>
  </div>
</div>

<div class=row-fluid>
  <div class="container-fluid">
    <div class="span9">
      <%= render 'watch/event_table' %>
    </div>
    <div class="span3">
      <div class="proper-content">
        <%= render 'watch/sidebar' %>
      </div>
    </div>
  </div> <%# container-fluid %>
</div> <%# row-fluid %>